# Nom du workflow 
name: Hello World
# l’evenement déclencheur 
on: [push]
# Définition des tâches (jobs) à exécuter
jobs:
  say_hello: # nom du job
    runs-on: ubuntu-latest # machine virtuelle (runner) utilisée : Ubuntu Linux
    steps: # suite d’étapes à exécuter
      - name: Print Hello # nom de l’étape
        run: echo "Bonjour depuis GitHub Actions !" # commande exécutée